print("Ola,bem vindo!!!")
nome = input("como gostaria que te chamasse? ")
print(f"seu nome é: {nome}" )
print(f"Prazer eu me chamo bot e vou iniciar o seu cadastro: {nome} ")
print("-----------------------") 
print("CADASTRO")
print("------------------------")
gmail = input("qual seu gmail por gentileza? ")
print(f"seu gmail é: {gmail} ")
escola = input ("aonde voce estuda? ")
print("--------------------------")
print(f"entao voce estuda no colegio: {escola} ")
ra = input ("voce sabe seu RA? se nao tudo bem! ")
print(f"entao seu RA é: {ra}")
print("--------------------------")
print(f"cadastro concluido: {ra}")