print("ola mundo!")
print("vou ser rico")
nome = input('qual é o seu nome? ')
print(nome)
idade = input('qual a sua idade jovem? ')
print(idade)
print("------------------")
print("Ola, seja bem vindo! Fique avontade ")
print("------------------")
nome = input ("Antes de iniciar o cadastro, qual o nome do senhor(a)? ")
print ("Seja muito bem vindo(a) ", nome  ) 
gmail = input ("Qual o seu gmail? ")
print (gmail)
print("--------------------")
print("Obrigado volte sempre!!! ")
print("---------------------")